#define TAPPING_TERM 200

#define PERMISSIVE_HOLD
// or
//#define HOLD_ON_OTHER_KEY_PRESS

#define COMBO_TERM 50 // TODO: Try defaulting to 200
#define MK_KINETIC_SPEED
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 7
#define MOUSEKEY_MOVE_DELTA 100
#define MOUSEKEY_INITIAL_SPEED 200
#define MOUSEKEY_BASE_SPEED 8000
#define MOUSEKEY_ACCELERATED_SPEED 3000

#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 16
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 32
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 48
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 8
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL

#define MOUSEKEY_MAX_SPEED 9
#define MOUSEKEY_TIME_TO_MAX 40

// TODO: Might be useful
//#define STRICT_LAYER_RELEASE
//#define NO_DEBUG
//#define NO_PRINT
