//
// Created by S2Ler on 18.08.23.
//

#ifndef QMK_FIRMWARE_KEY_CODES_H
#define QMK_FIRMWARE_KEY_CODES_H

#include "quantum.h"

#define LCG(kc) (QK_LCTL | QK_LGUI | (kc))
#define LCSG(kc) (QK_LCTL | QK_LGUI | (kc))

#define REDO (QK_LSFT | QK_LGUI | KC_Z)

#define FIND_CALLERS LCA(KC_H)
#define NAV_BACK LCG(KC_LEFT)
#define NAV_FORWARD LCG(KC_RIGHT)
#define TO_DEFINITION LCG(KC_J)
#define REINDENT LCTL(KC_I)
#define MOVE_LINE_UP LAG(KC_LEFT_BRACKET)
#define MOVE_LINE_DOWN LAG(KC_RIGHT_BRACKET)
#define REVEAL_IN LSG(KC_J)

#define LINE_START LCTL(KC_A)
#define LINE_END LCTL(KC_E)
#define SELECT_LINE_END RSG(KC_RIGHT)
#define SELECT_LINE_START RSG(KC_LEFT)
#define KILL_TO_LINE_END LCTL(KC_K)
#define NEXT_PLACEHOLDER LCTL(KC_SLASH)
#define WORD_START LCTL(KC_LEFT)
#define WORD_END LCTL(KC_RIGHT)
#define SELECT_WORD_START LSA(KC_LEFT)
#define SELECT_WORD_END LSA(KC_RIGHT)
#define SHOW_DOCUMENTATION (QK_LCTL | QK_LSFT | QK_LGUI | KC_SLASH)
#define FILE_STRUCTURE LCTL(KC_6)
#define XCODE_ACTION_POPUP SGUI(KC_A)
#define NEXT_APP_WINDOW LGUI(KC_GRAVE)

#define NEXT_WINDOW_TAB LCTL(KC_TAB)
#define PREV_WINDOW_TAB (QK_LCTL | QK_LSFT | KC_TAB)
#define NEXT_TAB SGUI(KC_RBRC)
#define PREV_TAB SGUI(KC_LBRC)

#define MV_TO_NEXT_WINDOW LSFT(KC_F18)
#define MV_TO_PREV_WINDOW KC_F18
#define RS_LEFT_HALF LGUI(KC_F18)
#define RS_RIGHT_HALF LCTL(KC_F18)
#define RS_BOTTOM_HALF (QK_LCTL | QK_LSFT | KC_F18)
#define RS_TOP_HALF (QK_LCTL | QK_LGUI | KC_F18)

#define ZOOM_IN LGUI(KC_KP_PLUS)
#define ZOOM_OUT LGUI(KC_MINUS)

#define APP_GIT_GUI MEH(KC_F17)
#define APP_PYCHARM LALT(KC_F17)
#define APP_MAIL (QK_LCTL | QK_LSFT | KC_F17)
#define APP_SLACK LSFT(KC_F17)
#define APP_BROWSER KC_F17
#define APP_XCODE LCTL(KC_F17)

#define APP_TERMINAL HYPR(KC_T)
#define ACT_SNIPPETS (QK_LCTL | QK_LSFT | KC_SPACE)
#define ACT_TODO HYPR(KC_I)
#define ACT_CLIPBOARD HYPR(KC_V)
#define ACT_NEW_NOTE HYPR(KC_N)
#define ACT_MAXIMIZE_WINDOW HYPR(KC_M)
#define ACT_SHOW_DESKTOP KC_F11
#define ACT_SHOW_NOTIFICATIONS LCAG(KC_F17)
#define ACT_SHORTCAT KC_F13
#define ACT_MENU_BAR SGUI(KC_SLASH)
#define ACT_MISSION_CONTROL HYPR(KC_UP)
#define ACT_APPLICATION_WINDOWS HYPR(KC_DOWN)
#define ACT_NEXT_DESKTOP HYPR(KC_RIGHT)
#define ACT_PREV_DESKTOP HYPR(KC_LEFT)
#define ACT_SIRI HYPR(KC_S)
#define ACT_SEARCH_FILES HYPR(KC_F)
#define ACT_DICTATION LSFT(KC_F5)
#define ACT_FREE_1 (QK_LCTL | QK_LSFT | KC_F16)
#define ACT_RAYCAST_AI KC_F16
#define ACT_RAYCAST_IMPROVE_WRITING LSFT(KC_F16)
#define ACT_RAYCAST_FIX_SPELLING LCTL(KC_F16)
#define ACT_FREE_0 LCG(KC_F17)

#define ACT_SWITCH_WINDOWS LSFT(KC_F13)
#define ACT_SELECTION_SCREENSHOT (QK_LSFT | QK_LGUI | KC_4)
#endif // QMK_FIRMWARE_KEY_CODES_H
